insert into task(employee_id, explanation)
values(1, 'Task ID 1');
insert into task(employee_id, explanation)
values(2, 'Task ID 2');
insert into task(employee_id, explanation)
values(3, 'Task ID 3');
insert into task(employee_id, explanation)
values(4, 'Task ID 4');
insert into task(employee_id, explanation)
values(5, 'Task ID 5');
insert into task(employee_id, explanation)
values(6, 'Task ID 6');